<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:atom="http://www.w3.org/2005/Atom">
  <xsl:output method="html" version="4.0" encoding="UTF-8" indent="yes" />
  <xsl:template name="format-date">
    <xsl:param name="date" />
    <xsl:variable name="short" select="substring($date, 1, 10)" />
    <xsl:variable name="year" select="substring($short, 1, 4)" />
    <xsl:variable name="month" select="substring($short, 6, 2)" />
    <xsl:variable name="day" select="substring($short, 9, 2)" />
    <xsl:value-of select="concat($year, ' 年 ', number($month), ' 月 ', number($day), ' 日')" />
  </xsl:template>
  <xsl:template match="/atom:feed">
    <html xmlns="http://www.w3.org/1999/xhtml" lang="en">
      <head>
        <title>Atom Feed | <xsl:value-of select="atom:title" /></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="48x48" href="/favicon-48x48.png" />
        <link rel="icon" type="image/png" sizes="192x192" href="/favicon-192x192.png" />
        <link rel="icon" type="image/png" sizes="512x512" href="/favicon-512x512.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="preload" href="/fonts/GeistVF.woff2" as="font" type="font/woff2" />
        <link rel="preload" href="/fonts/Lexend-VariableFont_wght.woff2" as="font" type="font/woff2" />
        <link rel="preload" href="/fonts/ZhudouSansVF-subset.woff2" as="font" type="font/woff2" />
        <link rel="preload" href="/fonts/GeistMono[wght].woff2" as="font" type="font/woff2" />
        <link rel="stylesheet" href="/fonts/ShangguSansSC-VF/result.css" />
        <link rel="stylesheet" href="/rss/rss.css" />
        <script src="/js/theme.js"></script>
      </head>
      <body>
        <header>
          <h1>
            <xsl:value-of select="atom:title" />
          </h1>
          <p class="subtitle">
            <xsl:value-of select="atom:subtitle" />
          </p>
          <a href="{atom:link[@rel='alternate']/@href}" class="button">
            <span>Visit site</span>
            <svg viewBox="0 0 24 24" aria-hidden="true" xmlns="http://www.w3.org/2000/svg">
              <path d="M7 17l10-10M13 7h4v4" />
              <path d="M17 7v0" />
            </svg>
          </a>
        </header>
        <main>
          <ul class="posts">
            <xsl:for-each select="atom:entry">
              <li class="post">
                <a class="post-link" href="{atom:link/@href}">
                  <span class="title">
                    <xsl:value-of select="atom:title" />
                  </span>
                </a>
                <div class="meta">
                  <time>
                    <span class="badge">更新于</span>
                    <xsl:call-template name="format-date">
                      <xsl:with-param name="date" select="atom:updated" />
                    </xsl:call-template>
                  </time>
                </div>
                <p class="summary">
                  <xsl:value-of select="atom:summary" />
                </p>
              </li>
            </xsl:for-each>
          </ul>
        </main>
        <div class="belonging">This is a RSS Feed generated by <a href="https://litos.vercel.app/"
            target="_blank">
            Litos</a>. RSS readers can use the URL in the address bar. </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>